### ISSUE TITLE
Set up tig stack for ot-dev monitoring

### ISSUE THREAD

**Issue by aloralove** [acep-uaf/camio-meter-streams#5]
- [x] get the git repo cloned on the ot-dev server
- [x] install docker on ot-dev
- [x] create a new branch 
- [x] add docker-compose file for telegraf influxdb and grafana
- [x] add telegraf.conf to grab data from the server for monitoring metrics
- [x] run images and containers
- [ ] get influxdb setup (had problem connecting to the browser. Couldn't shh tunnel. debugging continues...)
- [ ] get grafana setup (had problem connecting to the browser. Couldn't shh tunnel. debugging continues...)

**Comment by nicolemah99** [comment]
Not relevant to this repo anymore
